ColabUrl: https://colab.research.google.com/drive/1NkoAWWKxszBVp2m8cbBf5axavLkbqwTv
SameIDstart: 352
SameIDstartConfirm: false
close360whenStart: false
csvFile: account.csv
csvWithGmail: false
deleteWarning: false
functionSelect: 2
gmailDbName: gmail_tb.db
inputGmailTryTimes: 30
maxUser: 2000
trainDelay: 1
trainErrTryTimes: 150
trainID: 32
trainMaxWindows: 100
trainRestTime: 3600
trainRunConfirm: 50
trainRunDelay: 15
useGGFKZS: false
userID: 809
userPath: ./USER_DATA
webExePath: ./360Chrome/Chrome/Application/360chrome.exe
webUserPath: ./360Chrome/Chrome/Application/9.5.0.138/USER_DATA
